title: Amol Grover GSoC Report
email: frextrite@gmail.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: frextrite
github_username:  frextrite

# Build settings
markdown: kramdown
